services:
  indicmoe-training:
    image: nvcr.io/nvidia/pytorch:25.09-py3
    container_name: indicmoe-training
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_NAME=IndicMoE-3B-FP4
    volumes:
      - ./code:/workspace/code
      - ./data:/workspace/data
      - ./logs:/workspace/logs
      - ./configs:/workspace/configs
      - ./.env:/workspace/.env
      - ./setup_data_dirs.sh:/workspace/setup_data_dirs.sh
    shm_size: 32gb
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    working_dir: /workspace
    command: /bin/bash